Separate keyword arguments and positional arguments
sorah/corpshort pull request #2
Opened 2023-04-17 12:56 UTC by nekketsuuu

`Corpshort::Link#initialize` receives `data` argument as a positional argument: https://github.com/sorah/corpshort/blob/35e8d71f66851d311a6097c1755ed409ea50b573/lib/corpshort/link.rb#L15

So, for Ruby 3.0, I fixed some calls of `Corpshot::Link.new` which use keyword-argument syntax for `data` argument.

2023-04-17 12:57 UTC, sorah requested changes
can you change the `Link` to accept kwargs instead of hash?

2023-04-18 04:58 UTC, nekketsuuu commented
Sure! I changed like that https://github.com/sorah/corpshort/pull/2/commits/13ab1f8c2008c3fa88fcc17434c6875e1e64fa14

2023-04-18 04:59 UTC, sorah approved these changes

2023-04-18 04:59 UTC, merged

2023-04-18 05:21 UTC, nekketsuuu commented
Thanks~